package com.capgemini.selenium;// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class PactometroTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","C:\\Users\\amartino\\OneDrive - Capgemini\\Desktop\\ChromeDriver\\chromedriver.exe");
    driver = new ChromeDriver();
    driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void pactometro() {
    // Test name: pactometro
    // Step # | name | target | value
    // 1 | open | /pactometro/ | 
    driver.get("https://cursosdedesarrollo.com/pactometro/");
    // 2 | setWindowSize | 1936x1056 | 
    driver.manage().window().setSize(new Dimension(1936, 1056));
    // 3 | click | id=part-PP | 
    driver.findElement(By.id("part-PP")).click();
    // 4 | click | id=num-sies | 
    driver.findElement(By.id("num-sies")).click();
    // 5 | click | css=#part-Cup > img | 
    driver.findElement(By.cssSelector("#part-Cup > img")).click();
    // 6 | click | id=num-sies | 
    driver.findElement(By.id("num-sies")).click();
    // 7 | click | css=#part-PSOE > img | 
    driver.findElement(By.cssSelector("#part-PSOE > img")).click();
    // 8 | click | id=num-abst | 
    driver.findElement(By.id("num-abst")).click();
    // 9 | click | css=#part-Vox > img | 
    driver.findElement(By.cssSelector("#part-Vox > img")).click();
    // 10 | click | id=num-noes | 
    driver.findElement(By.id("num-noes")).click();
    // 11 | click | css=#part-Ciudadanos > img | 
    driver.findElement(By.cssSelector("#part-Ciudadanos > img")).click();
    // 12 | click | id=num-noes | 
    driver.findElement(By.id("num-noes")).click();
    // 13 | click | id=num-sies | 
    driver.findElement(By.id("num-sies")).click();
    // 14 | assertText | id=num-sies | 91
    assertEquals("91", driver.findElement(By.id("num-sies")).getText());
    // 15 | click | id=num-abst | 
    driver.findElement(By.id("num-abst")).click();
    // 16 | assertText | id=num-abst | 120
    assertEquals("120", driver.findElement(By.id("num-abst")).getText());
    // 17 | click | id=num-noes | 
    driver.findElement(By.id("num-noes")).click();
    // 18 | assertText | id=num-noes | 62
    assertEquals("62", driver.findElement(By.id("num-noes")).getText());
    // 19 | click | id=reset | 
    driver.findElement(By.id("reset")).click();
    // 20 | click | id=num-sies | 
    driver.findElement(By.id("num-sies")).click();
    // 21 | assertText | id=num-sies | 0
    assertEquals("0", driver.findElement(By.id("num-sies")).getText());
    // 22 | click | id=num-abst | 
    driver.findElement(By.id("num-abst")).click();
    // 23 | assertText | id=num-abst | 0
    assertEquals("0", driver.findElement(By.id("num-abst")).getText());
    // 24 | click | id=num-noes | 
    driver.findElement(By.id("num-noes")).click();
    // 25 | assertText | id=num-noes | 0
    assertEquals("0", driver.findElement(By.id("num-noes")).getText());
    // 26 | assertElementPresent | id=reset | 
    {
      List<WebElement> elements = driver.findElements(By.id("reset"));
      assert(elements.size() > 0);
    }
    // 27 | assertElementPresent | id=part-PP | 
    {
      List<WebElement> elements = driver.findElements(By.id("part-PP"));
      assert(elements.size() > 0);
    }
    // 28 | assertElementPresent | css=#part-PSOE > img | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("#part-PSOE > img"));
      assert(elements.size() > 0);
    }
    // 29 | assertElementPresent | id=sies | 
    {
      List<WebElement> elements = driver.findElements(By.id("sies"));
      assert(elements.size() > 0);
    }
    // 30 | assertElementPresent | id=abst | 
    {
      List<WebElement> elements = driver.findElements(By.id("abst"));
      assert(elements.size() > 0);
    }
    // 31 | assertElementPresent | id=noes | 
    {
      List<WebElement> elements = driver.findElements(By.id("noes"));
      assert(elements.size() > 0);
    }
  }
}
